variable "region_name" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "subnet1_cidr" {}
variable "subnet2_cidr" {}
variable "subnet3_cidr" {}
variable "subnet4_cidr" {}
variable "subnet5_cidr" {}
variable "subnet6_cidr" {}
variable "keypair_name" {}